name: moldrug
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ipykernel
  - ipython
  - ipywidgets
  - pip
  - python==3.9.*
  - nbsphinx
  - sphinx==5.3.0
  - conda-build
  # This is needed to make easy the documentation build.
  - vina
  - pip:
    - numpy<2
    - tqdm
    - pandas
    - rdkit
    - pyyaml
    - meeko
    - scipy
    - six
    - crem
    - requests
    - pytest
    - sphinx_copybutton
    - myst_nb
    - recommonmark
    - sphinx_book_theme